[bell]
animation = "EaseOutSine"
color = "#81A1C1"
duration = 400

[colors]
transparent_background_colors = false

[colors.bright]
black = "#686868"
blue = "#5CCFE6"
cyan = "#95E6CB"
green = "#A6CC70"
magenta = "#FFEE99"
red = "#F27983"
white = "#FFFFFF"
yellow = "#FFCC66"

[colors.normal]
black = "#191E2A"
blue = "#73D0FF"
cyan = "#95E6CB"
green = "#BAE67E"
magenta = "#FFD580"
red = "#FF3333"
white = "#C7C7C7"
yellow = "#FFA759"

[colors.primary]
background = "#2E3440"
foreground = "#CBCCC6"

[cursor]
blink_interval = 250
unfocused_hollow = true

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 16.0

[font.normal]
family = "monospace"

[mouse]
hide_when_typing = true

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

[terminal.shell]
args = ["--login"]
program = "/bin/bash"

[window]
decorations = "none"
opacity = 0.6
startup_mode = "Maximized"
title = "Home Sweet Home"

[terminal]

[keyboard]
bindings= [
    # by default C-backspace is the same as C-h, used as backspace
    # not all shells can get C-backspace for legacy reasons
    # but we can remap it in alacritty to C-w, which is exactly what I want it to be
    {key="Back", mods="Control", chars="\u0017"},
    {key="Delete", mods="Control", chars="\u001b\u0064"},
    {key="ArrowRight", mods="Control", chars="\u001b\u0066"},
    {key="ArrowLeft", mods="Control", chars="\u001b\u0062"},
    {key="Enter", chars="\u000d"},
    {key="Enter", mods="Shift", chars="\u000a"},
    {key="Delete", chars="\u0004"},
    {key="ArrowRight", chars="\u0006"},
    {key="ArrowLeft", chars="\u0002"},
    {key="ArrowDown", chars="\u000e"},
    {key="ArrowUp", chars="\u0010"},
    {key="Back", chars="\u0008"},
    {key="Home", chars="\u0001"},
    {key="End", chars="\u0005"},
]
