shared:
  terminals: &terminals
    - Gnome-terminal
    - Kitty
    - Alactritty

modmap:
  - name: sensible caps
    remap:
      Capslock: Control
      Control_L: Esc
keymap:
  - name: readline for everything
    application:
      not: *terminals
    remap:
      C-h: Backspace
      C-w: C-Backspace
      C-b: left
      M-b: C-left
      C-f: right
      C-l: right
      M-f: C-right
      C-n: down
      C-p: up
      C-m: Enter
      C-u: [SHIFT-HOME, Backspace]
      C-k: [HOME, SHIFT-END, Backspace]
      C-a: HOME
      C-e: END
      C-/: C-f
