echo configuration loading: Soenke Default # sometimes used for debugging

### --- note: single `#` is used for comments, usually at the end of the line
### --- note: double `##` is used to comment out lines of code, much like is convention in vimrc

# currently in debugging mode, shouldn't be committed like that
##set -x 

### --- looks
# set PS1, copied from git bash for windows at
# Program\ Files/Git/etc/bash.bashrc
[[ $(declare -p PS1 2>/dev/null | cut -c 1-11) = 'declare -x ' ]] || \
  export PS1='\[\e]0;\w\a\]\n\[\e[32m\]\u@\h \[\e[35m\]$MSYSTEM\[\e[0m\] \[\e[33m\]\w\[\e[0m\]\n'"${_ps1_symbol}"' '
unset _ps1_symbol

### --- file location stuff
# remember where the bash was started from
bashStartCD="${PWD}"
alias cdx='cd $bashStartCD'
#-- bookmarks
# defaults
tempCD="/d/temp"
vimCD="$HOME/.vim"
# specific to the machine, overwriting defaults
bashLocationsFile="$HOME/locationsForCD.bash"
if test -f $bashLocationsFile; then
  source $bashLocationsFile 
  echo "sourced" $bashLocationsFile
  journalCD="$writingCD/diary"
else
  echo "couldn't source" $bashLocationsFile "see ~/.vim/README.md under '#### Bash'"
fi

### --- source more scripts organised in files
cd $vimCD/bash 
source ./common.bash
for file in rc/*; do
  source $file
done

### --- final toughts
# I usually like to start my bash in my vimfiles
cdv 
# but when I call bash explicitly in a particular location I like to stay there
if [ $bashStartCD != "/" ]; then
  echo "not default location"
  cdx
fi

